#!/bin/bash

import os
import py_compile

# Get the filename from the environment variable
pyfile = os.getenv('PYFILE')

if pyfile:
    # Compile the Python file
    py_compile.compile(pyfile)

    # Rename the compiled file to include 'c' suffix
    compiled_filename = pyfile + 'c'
    os.rename('__pycache__' + os.sep + os.path.basename(pyfile)[:-3] + '.cpython-39.pyc', compiled_filename)
    print(f"Successfully compiled '{pyfile}' to '{compiled_filename}'")
else:
    print("Error: Environment variable $PYFILE is not set.")
