#!/bin/bash

# Check if PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable \$PYFILE is not set."
    exit 1
fi

# Compile the Python file
python3 -m py_compile "$PYFILE"

# Rename the compiled file
compiled_filename="${PYFILE}c"
mv "__pycache__/${PYFILE}__pycache__" "$compiled_filename"

echo "Compiling $PYFILE ..."
